export const supplies = [
  {
    "Supplier ID": 30001,
    "Supplier Name": "Tech Supplies Ltd.",
    Country: "China",
    "Contact Person": "Li Wei",
    "Contact Email": "liwei@techsupplies.cn",
  },
  {
    "Supplier ID": 30002,
    "Supplier Name": "Euro Electronics GmbH",
    Country: "Germany",
    "Contact Person": "Hans Müller",
    "Contact Email": "hans@euroelectronics.de",
  },
  {
    "Supplier ID": 30003,
    "Supplier Name": "Home Appliances Co.",
    Country: "Netherlands",
    "Contact Person": "Anika Janssen",
    "Contact Email": "anika@homeappliances.nl",
  },
  {
    "Supplier ID": 30004,
    "Supplier Name": "Nippon Electronics Inc.",
    Country: "Japan",
    "Contact Person": "Yuki Tanaka",
    "Contact Email": "yuki@nippon.co.jp",
  },
  {
    "Supplier ID": 30005,
    "Supplier Name": "Bharat Manufacturing",
    Country: "India",
    "Contact Person": "Ravi Kumar",
    "Contact Email": "ravi@bharatmanufacturing.in",
  },
  {
    "Supplier ID": 30006,
    "Supplier Name": "Asia Tech Exporters",
    Country: "Singapore",
    "Contact Person": "Aisha Lim",
    "Contact Email": "aisha@asiatech.sg",
  },
  {
    "Supplier ID": 30007,
    "Supplier Name": "Korea Supplies Corp.",
    Country: "South Korea",
    "Contact Person": "Ji-ho Kim",
    "Contact Email": "jiho@koreasupplies.kr",
  },
  {
    "Supplier ID": 30008,
    "Supplier Name": "Belgium Electronics SA",
    Country: "Belgium",
    "Contact Person": "Luc Dubois",
    "Contact Email": "luc@belgiumelectronics.be",
  },
  {
    "Supplier ID": 30009,
    "Supplier Name": "Brazil Tech Exports",
    Country: "Brazil",
    "Contact Person": "Ana Souza",
    "Contact Email": "ana@braziltechexports.br",
  },
  {
    "Supplier ID": 30010,
    "Supplier Name": "Aussie Tech Solutions",
    Country: "Australia",
    "Contact Person": "Chloe Brown",
    "Contact Email": "chloe@aussietech.com.au",
  },
  {
    "Supplier ID": 30011,
    "Supplier Name": "Hong Kong Trading Co.",
    Country: "Hong Kong",
    "Contact Person": "Wing Lau",
    "Contact Email": "wing@hongkongtrading.hk",
  },
  {
    "Supplier ID": 30012,
    "Supplier Name": "Dubai Tech Supplies",
    Country: "UAE",
    "Contact Person": "Ahmed Al-Farsi",
    "Contact Email": "ahmed@dubaitech.ae",
  },
  {
    "Supplier ID": 30013,
    "Supplier Name": "Dutch Electronics BV",
    Country: "Netherlands",
    "Contact Person": "Maarten de Vries",
    "Contact Email": "maarten@dutchelectronics.nl",
  },
  {
    "Supplier ID": 30014,
    "Supplier Name": "Japan Tech Exporters",
    Country: "Japan",
    "Contact Person": "Satoshi Nakamura",
    "Contact Email": "satoshi@japantech.jp",
  },
  {
    "Supplier ID": 30015,
    "Supplier Name": "India Electronics Pvt.",
    Country: "India",
    "Contact Person": "Priya Sharma",
    "Contact Email": "priya@indiaelectronics.in",
  },
  {
    "Supplier ID": 30016,
    "Supplier Name": "Singapore Tech Pte Ltd",
    Country: "Singapore",
    "Contact Person": "Ken Wong",
    "Contact Email": "ken@singaporetech.sg",
  },
  {
    "Supplier ID": 30017,
    "Supplier Name": "Korea Electronics Inc.",
    Country: "South Korea",
    "Contact Person": "Min-seo Park",
    "Contact Email": "minseo@koreaelectronics.kr",
  },
  {
    "Supplier ID": 30018,
    "Supplier Name": "Belgium Tech Exporters",
    Country: "Belgium",
    "Contact Person": "Sophie Verhoeven",
    "Contact Email": "sophie@belgiumtechexporters.be",
  },
  {
    "Supplier ID": 30019,
    "Supplier Name": "Brazil Electronics SA",
    Country: "Brazil",
    "Contact Person": "Pedro Costa",
    "Contact Email": "pedro@brazilelectronics.br",
  },
  {
    "Supplier ID": 30020,
    "Supplier Name": "Australia Tech Ltd.",
    Country: "Australia",
    "Contact Person": "Ella Wilson",
    "Contact Email": "ella@australiatech.com.au",
  },
];

export const shipments = [
  {
    "Shipment ID": 10001,
    Date: "2024-01-01",
    Origin: "Shanghai",
    Destination: "Los Angeles",
    "Product ID": 20001,
    Quantity: 1000,
    "Supplier ID": 30001,
    "Transport Mode": "Sea",
  },
  {
    "Shipment ID": 10002,
    Date: "2024-01-03",
    Origin: "Hamburg",
    Destination: "New York",
    "Product ID": 20002,
    Quantity: 500,
    "Supplier ID": 30002,
    "Transport Mode": "Air",
  },
  {
    "Shipment ID": 10003,
    Date: "2024-01-05",
    Origin: "Rotterdam",
    Destination: "Miami",
    "Product ID": 20003,
    Quantity: 750,
    "Supplier ID": 30003,
    "Transport Mode": "Sea",
  },
  {
    "Shipment ID": 10004,
    Date: "2024-01-07",
    Origin: "Tokyo",
    Destination: "San Francisco",
    "Product ID": 20004,
    Quantity: 1200,
    "Supplier ID": 30004,
    "Transport Mode": "Air",
  },
  {
    "Shipment ID": 10005,
    Date: "2024-01-10",
    Origin: "Mumbai",
    Destination: "Houston",
    "Product ID": 20005,
    Quantity: 1100,
    "Supplier ID": 30005,
    "Transport Mode": "Sea",
  },
  {
    "Shipment ID": 10006,
    Date: "2024-01-12",
    Origin: "Singapore",
    Destination: "Seattle",
    "Product ID": 20006,
    Quantity: 650,
    "Supplier ID": 30006,
    "Transport Mode": "Air",
  },
  {
    "Shipment ID": 10007,
    Date: "2024-01-15",
    Origin: "Busan",
    Destination: "Los Angeles",
    "Product ID": 20007,
    Quantity: 850,
    "Supplier ID": 30007,
    "Transport Mode": "Sea",
  },
  {
    "Shipment ID": 10008,
    Date: "2024-01-17",
    Origin: "Antwerp",
    Destination: "Chicago",
    "Product ID": 20008,
    Quantity: 900,
    "Supplier ID": 30008,
    "Transport Mode": "Air",
  },
  {
    "Shipment ID": 10009,
    Date: "2024-01-20",
    Origin: "Santos",
    Destination: "New Orleans",
    "Product ID": 20009,
    Quantity: 1300,
    "Supplier ID": 30009,
    "Transport Mode": "Sea",
  },
  {
    "Shipment ID": 10010,
    Date: "2024-01-22",
    Origin: "Sydney",
    Destination: "San Diego",
    "Product ID": 20010,
    Quantity: 1400,
    "Supplier ID": 30010,
    "Transport Mode": "Air",
  },
  {
    "Shipment ID": 10011,
    Date: "2024-01-25",
    Origin: "Hong Kong",
    Destination: "Vancouver",
    "Product ID": 20011,
    Quantity: 1500,
    "Supplier ID": 30011,
    "Transport Mode": "Sea",
  },
  {
    "Shipment ID": 10012,
    Date: "2024-01-28",
    Origin: "Dubai",
    Destination: "Toronto",
    "Product ID": 20012,
    Quantity: 1600,
    "Supplier ID": 30012,
    "Transport Mode": "Air",
  },
  {
    "Shipment ID": 10013,
    Date: "2024-01-30",
    Origin: "Rotterdam",
    Destination: "Houston",
    "Product ID": 20013,
    Quantity: 1000,
    "Supplier ID": 30013,
    "Transport Mode": "Sea",
  },
  {
    "Shipment ID": 10014,
    Date: "2024-02-01",
    Origin: "Tokyo",
    Destination: "Los Angeles",
    "Product ID": 20014,
    Quantity: 800,
    "Supplier ID": 30014,
    "Transport Mode": "Air",
  },
  {
    "Shipment ID": 10015,
    Date: "2024-02-04",
    Origin: "Mumbai",
    Destination: "New York",
    "Product ID": 20015,
    Quantity: 1100,
    "Supplier ID": 30015,
    "Transport Mode": "Sea",
  },
  {
    "Shipment ID": 10016,
    Date: "2024-02-07",
    Origin: "Singapore",
    Destination: "Miami",
    "Product ID": 20016,
    Quantity: 650,
    "Supplier ID": 30016,
    "Transport Mode": "Air",
  },
  {
    "Shipment ID": 10017,
    Date: "2024-02-10",
    Origin: "Busan",
    Destination: "San Francisco",
    "Product ID": 20017,
    Quantity: 850,
    "Supplier ID": 30017,
    "Transport Mode": "Sea",
  },
  {
    "Shipment ID": 10018,
    Date: "2024-02-13",
    Origin: "Antwerp",
    Destination: "Houston",
    "Product ID": 20018,
    Quantity: 900,
    "Supplier ID": 30018,
    "Transport Mode": "Air",
  },
  {
    "Shipment ID": 10019,
    Date: "2024-02-15",
    Origin: "Santos",
    Destination: "Seattle",
    "Product ID": 20019,
    Quantity: 1300,
    "Supplier ID": 30019,
    "Transport Mode": "Sea",
  },
  {
    "Shipment ID": 10020,
    Date: "2024-02-18",
    Origin: "Sydney",
    Destination: "Chicago",
    "Product ID": 20020,
    Quantity: 1400,
    "Supplier ID": 30020,
    "Transport Mode": "Air",
  },
];

export const products = [
  {
    "Product ID": 20001,
    "Product Name": "Laptop",
    category: "Electronics",
    "Unit Price": 700,
    "Stock Quantity": 5000,
  },
  {
    "Product ID": 20002,
    "Product Name": "Mobile Phone",
    category: "Electronics",
    "Unit Price": 400,
    "Stock Quantity": 8000,
  },
  {
    "Product ID": 20003,
    "Product Name": "Refrigerator",
    category: "Home Appliance",
    "Unit Price": 900,
    "Stock Quantity": 3000,
  },
  {
    "Product ID": 20004,
    "Product Name": "Air Conditioner",
    category: "Home Appliance",
    "Unit Price": 600,
    "Stock Quantity": 2500,
  },
  {
    "Product ID": 20005,
    "Product Name": "Washing Machine",
    category: "Home Appliance",
    "Unit Price": 500,
    "Stock Quantity": 4000,
  },
  {
    "Product ID": 20006,
    "Product Name": "Television",
    category: "Electronics",
    "Unit Price": 450,
    "Stock Quantity": 7000,
  },
  {
    "Product ID": 20007,
    "Product Name": "Microwave Oven",
    category: "Home Appliance",
    "Unit Price": 200,
    "Stock Quantity": 6000,
  },
  {
    "Product ID": 20008,
    "Product Name": "Smart Watch",
    category: "Electronics",
    "Unit Price": 150,
    "Stock Quantity": 9000,
  },
  {
    "Product ID": 20009,
    "Product Name": "Blender",
    category: "Home Appliance",
    "Unit Price": 100,
    "Stock Quantity": 3500,
  },
  {
    "Product ID": 20010,
    "Product Name": "Vacuum Cleaner",
    category: "Home Appliance",
    "Unit Price": 250,
    "Stock Quantity": 4500,
  },
  {
    "Product ID": 20011,
    "Product Name": "Tablet",
    category: "Electronics",
    "Unit Price": 300,
    "Stock Quantity": 5000,
  },
  {
    "Product ID": 20012,
    "Product Name": "Headphones",
    category: "Electronics",
    "Unit Price": 80,
    "Stock Quantity": 10000,
  },
  {
    "Product ID": 20013,
    "Product Name": "Printer",
    category: "Electronics",
    "Unit Price": 120,
    "Stock Quantity": 4000,
  },
  {
    "Product ID": 20014,
    "Product Name": "Camera",
    category: "Electronics",
    "Unit Price": 500,
    "Stock Quantity": 3000,
  },
  {
    "Product ID": 20015,
    "Product Name": "Smart Speaker",
    category: "Electronics",
    "Unit Price": 100,
    "Stock Quantity": 7000,
  },
  {
    "Product ID": 20016,
    "Product Name": "Gaming Console",
    category: "Electronics",
    "Unit Price": 350,
    "Stock Quantity": 2000,
  },
  {
    "Product ID": 20017,
    "Product Name": "Monitor",
    category: "Electronics",
    "Unit Price": 200,
    "Stock Quantity": 6000,
  },
  {
    "Product ID": 20018,
    "Product Name": "Keyboard",
    category: "Electronics",
    "Unit Price": 50,
    "Stock Quantity": 8000,
  },
  {
    "Product ID": 20019,
    "Product Name": "Mouse",
    category: "Electronics",
    "Unit Price": 30,
    "Stock Quantity": 10000,
  },
  {
    "Product ID": 20020,
    "Product Name": "External Hard Drive",
    category: "Electronics",
    "Unit Price": 100,
    "Stock Quantity": 5000,
  },
];
